/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home/bin/jpackage --type pkg \
  --input ./input-pv/ \
  --resource-dir ./resources-pv/ \
  --main-jar PornViewer.jar \
  --main-class com.plovdev.pornviewer.Launcher \
  --name "PornViewer" \
  --app-version "1.7.12" \
  --vendor "PlovDev" \
  --copyright "(c) 2026 PlovDev. All rights reserved." \
  --description "Secure and anonime 18+ video viewer with encrypting and plugins support" \
  --dest dist \
  --icon ./files/PornViewer.icns \
  --java-options "-Xmx2G" \
  --java-options "-Dfile.encoding=UTF-8" \
  --java-options "-Dapple.laf.useScreenMenuBar=true" \
  --java-options "-Dcom.apple.mrj.application.apple.menu.about.name=PornViewer" \
  --java-options "--enable-native-access=ALL-UNNAMED" \
  --mac-package-identifier "com.plovdev.pornviewer" \
  --mac-package-name "PornViewer" \
  --runtime-image ./files/pv-jre \
  --mac-app-category "public.app-category.entertainment" \
  --license-file ./files/LICENSE.txt \
  --about-url "https://github.com/plovdev/PornViewer" \
  --file-associations ./files/video-assoc.properties \
  --verbose