<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.plovdev.pornviewer</groupId>
        <artifactId>pornviewer-root</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>http</artifactId>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <okhhtp.version>5.3.2</okhhtp.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp-bom</artifactId>
                <version>${okhhtp.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.plovdev.pornviewer</groupId>
            <artifactId>core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.plovdev.pornviewer</groupId>
            <artifactId>database</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.plovdev.pornviewer</groupId>
            <artifactId>pvvasupport</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.plovdev.pornviewer</groupId>
            <artifactId>pvvfsupport</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp-jvm</artifactId>
        </dependency>
    </dependencies>
</project>