<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.plovdev.pornviewer</groupId>
        <artifactId>pornviewer-root</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>app</artifactId>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <logback.version>1.5.32</logback.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.plovdev.pornviewer</groupId>
            <artifactId>database</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.plovdev.pornviewer</groupId>
            <artifactId>security</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.plovdev.pornviewer</groupId>
            <artifactId>pvvasupport</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.plovdev.pornviewer</groupId>
            <artifactId>http</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.plovdev.pornviewer</groupId>
            <artifactId>server</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.0</version>
                <configuration>
                    <dependencyReducedPomLocation>${project.build.directory}/dependency-reduced-pom.xml</dependencyReducedPomLocation>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>org.plovdev.pvvacli.Main</mainClass>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                        <exclude>META-INF/*.EC</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <createSourcesJar>false</createSourcesJar>
                            <shadedArtifactAttached>false</shadedArtifactAttached>
                            <minimizeJar>false</minimizeJar>
                            <finalName>pvva-cli</finalName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>